apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registration-mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
