apiVersion: v1
kind: Secret
metadata:
  name: registration-mongodb-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password123
  MONGO_INITDB_DATABASE: registration_db
