package com.ibm.fscc.employeeservice.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Null;
import lombok.Data;

@Data
public class EmployeeDto {
    @Null(message = "ID must be generated by the system")
    private Long id;

    // Generated internally for client calls, preserved for internal service calls
    private String userId;

    @NotBlank(message = "First name cannot be empty")
    private String firstName;

    @NotBlank(message = "Last name cannot be empty")
    private String lastName;

    @NotBlank(message = "Address cannot be empty")
    private String address;

    @NotBlank(message = "City cannot be empty")
    private String city;

    @NotBlank(message = "State cannot be empty")
    private String state;

    @NotBlank(message = "Zip code cannot be empty")
    private String zip;

    @NotBlank(message = "Cell phone cannot be empty")
    private String cellPhone;

    @NotBlank(message = "Home phone cannot be empty")
    private String homePhone;

    @NotBlank(message = "Email cannot be empty")
    @Email(message = "Invalid email format")
    private String email;

    // Set to default of "USER" in service layer
    private String role;
}
